version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODEL=phi3
    ports:
      - "8000:8000"  # Map host port 80 to container port 8000
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_models: